"""changed administrator info

Revision ID: 21c0063a8143
Revises: 
Create Date: 2026-08-03 12:36:09.115123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21c0063a8143'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('minerals',
    sa.Column('mineral_id', sa.Integer(), nullable=False),
    sa.Column('mineral_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('mineral_id')
    )
    op.create_table('mining_sites',
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=150), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('depth', sa.String(length=50), nullable=True),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.Column('yield_estimate', sa.String(length=100), nullable=True),
    sa.Column('water_table', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('site_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('certificates',
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('certificate_number', sa.String(length=100), nullable=False),
    sa.Column('certificate_name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('issuer', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['mining_sites.site_id'], ),
    sa.PrimaryKeyConstraint('certificate_id'),
    sa.UniqueConstraint('certificate_number')
    )
    op.create_table('harvest_records',
    sa.Column('harvest_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('mineral_id', sa.Integer(), nullable=False),
    sa.Column('batch_code', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=False),
    sa.Column('method', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('harvest_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mineral_id'], ['minerals.mineral_id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['mining_sites.site_id'], ),
    sa.PrimaryKeyConstraint('harvest_id'),
    sa.UniqueConstraint('batch_code')
    )
    op.create_table('site_records',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('mineral_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mineral_id'], ['minerals.mineral_id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['mining_sites.site_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=False),
    sa.Column('vehicle_type', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['mining_sites.site_id'], ),
    sa.PrimaryKeyConstraint('vehicle_id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_table('shipments',
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('shipment_code', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=150), nullable=False),
    sa.Column('destination', sa.String(length=150), nullable=False),
    sa.Column('cargo', sa.String(length=150), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('vessel', sa.String(length=150), nullable=False),
    sa.Column('shipment_date', sa.Date(), nullable=False),
    sa.Column('estimated_arrival', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['mining_sites.site_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('shipment_id'),
    sa.UniqueConstraint('shipment_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipments')
    op.drop_table('vehicles')
    op.drop_table('site_records')
    op.drop_table('harvest_records')
    op.drop_table('certificates')
    op.drop_table('users')
    op.drop_table('mining_sites')
    op.drop_table('minerals')
    # ### end Alembic commands ###
